In [1]:
import numpy as np
import pandas as pd

In [2]:
book=pd.read_csv('BX-Books.csv', sep=';', error_bad_lines=False, encoding='latin-1')

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.p

In [3]:
book=book[['ISBN','Book-Title','Book-Author']]
book.rename(columns={'Book-Title':'Book Name', 'Book-Author':'Author'}, inplace=True)

In [4]:
book.head(2)

ISBN            Book Name                Author
0  0195153448  Classical Mythology    Mark P. O. Morford
1  0002005018         Clara Callan  Richard Bruce Wright

In [5]:
ratings=pd.read_csv('BX-Book-Ratings.csv', sep=';',encoding='latin-1')
ratings.head(2)

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [6]:
ratings.rename(columns={'User-ID':'user_id','Book-Rating':'rating'}, inplace=True)
ratings.head(2)

user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5

In [7]:
count=ratings['user_id'].value_counts()
ratings=ratings[ratings['user_id'].isin(count[count>200].index)]
len(ratings)

526356

In [8]:
ratings_with_bookname=ratings.merge(book, on='ISBN')
ratings_with_bookname

user_id        ISBN  rating  \
0        277427  002542730X      10   
1          3363  002542730X       0   
2         11676  002542730X       6   
3         12538  002542730X      10   
4         13552  002542730X       0   
5         16795  002542730X       0   
6         24194  002542730X       0   
7         25981  002542730X       0   
8         26535  002542730X       0   
9         28204  002542730X       0   
10        30533  002542730X       0   
11        31826  002542730X       0   
12        41084  002542730X       7   
13        43246  002542730X       0   
14        44728  002542730X       0   
15        51883  002542730X       0   
16        52584  002542730X      10   
17        55548  002542730X       0   
18        60244  002542730X       0   
19        71712  002542730X       6   
20        77809  002542730X       0   
21        80538  002542730X       7   
22        81045  002542730X       0   
23        82407  002542730X       0   
24        82831  002542730X       0   
25        86243  002542730X       7   
26        88733  002542730X       0   
27       110934  002542730X       6   
28       111947  002542730X       0   
29       112026  002542730X       0   
...         ...         ...     ...   
487641   275970  158469047X      10   
487642   275970  1585673773       0   
487643   275970  1585674168       0   
487644   275970  1586210661       9   
487645   275970  1586214349       8   
487646   275970  1586420488       0   
487647   275970  1586632043      10   
487648   275970  1590510399       0   
487649   275970  1592231411       0   
487650   275970  159228275X       0   
487651   275970  1592530192       0   
487652   275970  1840001909       0   
487653   275970  1840910488       0   
487654   275970  1843090104       0   
487655   275970  1845170423       7   
487656   275970  1854106252       0   
487657   275970  1854795937       0   
487658   275970  185649814X       7   
487659   275970  1859847897       0   
487660   275970  1875137750       0   
487661   275970  1879424428       0   
487662   275970  1880837927       0   
487663   275970  1886778191       0   
487664   275970  188717897X       0   
487665   275970  1888889047       0   
487666   275970  1892145022       0   
487667   275970  1931868123       0   
487668   275970  3411086211      10   
487669   275970  3829021860       0   
487670   275970  4770019572       0   

                                                Book Name  \
0       Politically Correct Bedtime Stories: Modern Ta...   
1       Politically Correct Bedtime Stories: Modern Ta...   
2       Politically Correct Bedtime Stories: Modern Ta...   
3       Politically Correct Bedtime Stories: Modern Ta...   
4       Politically Correct Bedtime Stories: Modern Ta...   
5       Politically Correct Bedtime Stories: Modern Ta...   
6       Politically Correct Bedtime Stories: Modern Ta...   
7       Politically Correct Bedtime Stories: Modern Ta...   
8       Politically Correct Bedtime Stories: Modern Ta...   
9       Politically Correct Bedtime Stories: Modern Ta...   
10      Politically Correct Bedtime Stories: Modern Ta...   
11      Politically Correct Bedtime Stories: Modern Ta...   
12      Politically Correct Bedtime Stories: Modern Ta...   
13      Politically Correct Bedtime Stories: Modern Ta...   
14      Politically Correct Bedtime Stories: Modern Ta...   
15      Politically Correct Bedtime Stories: Modern Ta...   
16      Politically Correct Bedtime Stories: Modern Ta...   
17      Politically Correct Bedtime Stories: Modern Ta...   
18      Politically Correct Bedtime Stories: Modern Ta...   
19      Politically Correct Bedtime Stories: Modern Ta...   
20      Politically Correct Bedtime Stories: Modern Ta...   
21      Politically Correct Bedtime Stories: Modern Ta...   
22      Politically Correct Bedtime Stories: Modern Ta...   
23      Politically Correct Bedtime Stories: Modern Ta...   
24      Politically Correct Bedtime Stories: Modern Ta...   
25 

In [9]:
book_num_ratings=ratings_with_bookname.groupby('Book Name')['rating'].agg('count').reset_index().rename(columns={'rating':'num_rating'})

In [10]:
salman=ratings_with_bookname.merge(book_num_ratings, on='Book Name')

In [11]:
srk=salman[salman['num_rating']>=50]

In [12]:
srk.drop_duplicates(['user_id','Book Name'], inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [13]:
len(srk)

59850

In [14]:
aamir=srk.pivot_table(index='Book Name', columns='user_id', values='rating').fillna(0)

In [15]:
aamir.shape

(742, 888)

In [ ]:
aamir.head()

In [16]:
from scipy.sparse import csr_matrix
ranbir=csr_matrix(aamir)

In [17]:
type(ranbir)

scipy.sparse.csr.csr_matrix

In [18]:
from sklearn.neighbors import NearestNeighbors

nn=NearestNeighbors(metric='cosine', algorithm='brute')

In [19]:
nn.fit(ranbir)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [20]:
distances,books=nn.kneighbors(aamir.iloc[0,:].values.reshape(1,888), n_neighbors=6)

In [21]:
books=books.ravel()
books

array([  0,  54, 575, 526, 321, 668], dtype=int64)

In [22]:
for i in books:
    print(aamir.index[i])

1984
Animal Farm
The Handmaid's Tale
The Catcher in the Rye
Lord of the Flies
The Vampire Lestat (Vampire Chronicles, Book II)


In [23]:
np.where(aamir.index=='1984')

(array([0], dtype=int64),)

In [24]:
np.where(aamir.index=='Animal Farm')

(array([54], dtype=int64),)

In [25]:
np.where(aamir.index=='Animal Farm')[0]

array([54], dtype=int64)

In [26]:
np.where(aamir.index=='Animal Farm')[0][0]

54

In [27]:
def suggest(name):
    book_id=np.where(aamir.index==name)[0][0]
    distance,books=nn.kneighbors(aamir.iloc[book_id,:].values.reshape(1,888),n_neighbors=6)
    
    for i in books.ravel():
        print(aamir.index[i])

In [ ]:
name=input('Enter A book name :-')
suggest(name)